# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.7.3

clone:
 depth: full
 
pipelines:
  default:
    #- step:
       # name: "Build ZIP"
      #  script:
           #- zipfile="ninthapp"
           #- dir="./"  #"ninth_project/"
           #- apt-get install zip
           #- zip -r $zipfile.zip $dir
           #- python -c "import shutil;shutil.make_archive('$zipfile','zip',root_dir='.', base_dir='$dir')"
          # - zip -r ninthapp.zip ./ #index.html appspec.yml
        #artifacts:
     #        - ninthapp.zip
    #- step:
     #       name: Build and test
      #      image: maven:3
       #     caches: 
        #      - maven
         #   script:
          #    - mvn -B clean verify
    #- step:
     #       name: Create artifact
      #      script:
       #       - tar czfv application.tgz pom.xml ./        
    - step:
        name: "Prodution"
        caches:
          - pip
        script: # Modify the commands below to build your repository.
          - pip install -r requirements.txt
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
          #- pipe: atlassian/heroku-deploy:1.1.0
           # variables:
            #    HEROKU_API_KEY: $HEROKU_API_KEY
             #   HEROKU_APP_NAME: $HEROKU_APP_NAME
              #  #LOCAL_PATH: "./"
               # ZIP_FILE: "ninth_project.tar.gz"  #"ninthapp.zip"
            
