# Generated by Django 2.1.4 on 2019-10-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctagg',
            options={'verbose_name': 'DocName', 'verbose_name_plural': 'DocNames'},
        ),
        migrations.AddField(
            model_name='doctagg',
            name='dateDoc',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
