# Generated by Django 2.2.6 on 2019-10-14 18:03

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('doctag', '0002_auto_20191011_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctagg',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
    ]
