# Generated by Django 2.2.6 on 2019-10-28 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name1', models.CharField(max_length=50)),
                ('last_name1', models.CharField(max_length=128)),
                ('nphone1', models.CharField(max_length=13)),
                ('nphone2', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=254)),
                ('driverslicense', models.CharField(max_length=3)),
                ('address', models.CharField(max_length=254)),
                ('neighborHood', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=9)),
                ('maritalStatus', models.CharField(max_length=128)),
                ('levelStudy', models.CharField(max_length=128)),
                ('lInstitution', models.CharField(max_length=128)),
                ('lyearFinish', models.CharField(max_length=4)),
                ('course', models.CharField(max_length=128)),
                ('cInstitution', models.CharField(max_length=128)),
                ('cyearFinish', models.CharField(max_length=4)),
                ('studyTime', models.CharField(max_length=5)),
                ('company', models.CharField(max_length=128)),
                ('function', models.CharField(max_length=128)),
                ('worktime', models.CharField(max_length=128)),
                ('functionDescribe', models.CharField(max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
